### ISSUE TITLE
close / open all folders

### ISSUE THREAD

**Issue by Dammmien** [thehogfather/brackets-code-folding#10]
Is there a way to close or open all files at once?
If not, is it planned in a future release?

Anyway thank you for this plugin, it is very useful.

**Comment by jonnypixel** [comment]
I made a folder called snippets / php,mysql,js,css

Then i opened that folder. I find it helpful for now. But i also googled this and i think a simple option to not show anything on startup would be better. Sometimes people don't want anything but the ability to load one off files to edit.
