### ISSUE TITLE
Collapse Problems

### ISSUE THREAD

**Issue by assunluis** [thehogfather/brackets-code-folding#112]
It's possible to add collapsed remember feature? When I collapse something and close de editor and reopened it again, it forgets all my collapse regions and expands everything.

**Comment by thehogfather** [comment]
That feature already exists. Can you check View > Code Folding settings and ensure that the "save fold states" options is ticked? If that does not solve the problem then some information about your setup and the steps needed to reproduce the issue would be useful (e.g., OS, Brackets version etc).

**Comment by assunluis** [comment]
Thanks thehogfather, the "save fold states" was unchecked. The plugin is working properly.
