### ISSUE TITLE
Background color - "Highlight Active Line"

### ISSUE THREAD

**Issue by Ezneh** [thehogfather/brackets-code-folding#113]
Hello, I have found a small issue with your extension. As you can see on the attached image, the background-color doesn't fit the color of the main brackets theme on a selected line, with the option "Highlight Active Line" activated.
This doesn't happen when the option is deactivated. 

Also I don't know if it only happens with darker themes of Brackets or with all available themes. Maybe it has to be checked too.

![brackets-folding](https://cloud.githubusercontent.com/assets/1930305/5737515/01c481e0-9be2-11e4-9fa2-105be3bf7ea1.PNG)

**Comment by thehogfather** [comment]
What theme are you using? It appears to be fine on the default brackets dark theme on my system.

**Comment by Ezneh** [comment]
The theme I am using right now is "Visual Studio Dark". Maybe the problem comes only from this theme, I will check with another one.

**Comment by Ezneh** [comment]
Ok, just to let you know, I resolved the issue by tweaking a little bit the theme. Sorry for the inconvenience =)

**Comment by thehogfather** [comment]
Thanks. It might be worth sending a pull request to the Visual Studio theme - especially if it is just a matter of updating css.

**Comment by Ezneh** [comment]
Yes, you are right. I'll do it asap.
