### ISSUE TITLE
Fold gutter gaps.

### ISSUE THREAD

**Issue by dustindowell22** [thehogfather/brackets-code-folding#114]
These might be related to the other issue I posted #111, about the temporary extra space next to the active line highlight.

When the window is inactive I get this gap in the fold gutter:
![image](http://cl.ly/image/013R0432202B/Screen%20Shot%202015-01-18%20at%2011.53.46%20PM.png)

When the window is inactive and the active line is on the fold gutter I get this:
![image](http://cl.ly/image/3y343h0Y3v3M/Screen%20Shot%202015-01-18%20at%2011.55.11%20PM.png)

The first thing that comes to mind would be making the fold gutter background transparent. I haven't had time to look at the code in depth, but it looks like that might be possible. If that fixed the problem it might be possible to reverse the change made in #111 to update the line cache.

**Comment by thehogfather** [comment]
What theme are you using? I can't seem to reproduce on the default brackets dark theme.

**Comment by dustindowell22** [comment]
I'm using Neon, a theme of mine, but I tested a few others and I see the same issue in Atom Light / Atom Dark.

**Comment by thehogfather** [comment]
Not 100% sure what the cause is. Does the issue go away if you explicitly style the height of .CodeMirror-foldgutter-blank, .CodeMirror-foldgutter-open etc ..?

**Comment by dustindowell22** [comment]
I tried your fix but it was off by 1px for me and it was really bugging me, so I spent some time in the debugger and found out that this class, the class wrapping `.CodeMirror-foldgutter-open`, height wasn't defined, so I changed it to this:

    .CodeMirror-gutter-elt {
      height: 1.375rem;
    }

The font size gets weird in this area too, for some reason, so I had to specify rems, to prevent it from scaling incorrectly.

I'm not sure how it should be handled though. Whether it should be a theme fix or a Cold Folding fix, or even a Bracket's bug, because I think `.CodeMirror-gutter-elt` is a Brackets class, right?

But at least there's an issue now for other themer's to discover.

**Comment by thehogfather** [comment]
Good shout. I will add the height property for `.CodeMirror-gutter-elt`  to the code-folding css. It is a CodeMirror library class.

Out of interest did you manage to find out why the issue was only present when the editor was inactive?

**Comment by dustindowell22** [comment]
I went back and poked around more and found this:

![image](http://cl.ly/image/261c0o0f0B3c/Screen%20Shot%202015-01-20%20at%2011.49.32%20PM.png)

This CSS goes away when not in focus, but I can't imagine why.
