### ISSUE TITLE
Extension error after closing brackets and starting it again

### ISSUE THREAD

**Issue by jcgallaher** [thehogfather/brackets-code-folding#115]
For some reason I'm getting an extension error and it won't load again after I close Brackets and start it again. I've reproduced the error several times by installing code folding, trying it out (It works fine), closing Brackets, and then opening it again. The code folding arrows won't appear and when I go into the extension's manager and click on installed, code folding will have an error next to it, that says extension error.

I'm running Windows 8.1

**Comment by thehogfather** [comment]
I just tested on my windows 8.1 vm and I cannot reproduce the issue. I have a few questions.
  1.  Are you running Brackets stable or development release (bleeding edge from git master)?
        *  If you are running the dev release, can you make sure there is no copy of the codefolding extension in the brackets src folder e.g., in `src/extensions/dev`
  2.  Does it make a difference when you manually install the extension (open the extensions folder by `Help > Show Extensions Folder` then place the [codefolding extension](https://github.com/thehogfather/brackets-code-folding/archive/master.zip) folder in the `user` folder)
  3.  In the past I have had intermittent issues that are as a result of conflicts with other extensions. Can you still reproduce this issue consistently if it is the only extension installed?

**Comment by jcgallaher** [comment]
I isolated the issue to the Minify More https://github.com/Fornace/minify-more When I uninstalled it and restarted Brackets Code Folding was working fine. Interestingly, when re-installed Minify More, code folding still works. So I'm figuring its an issue with minify more.

I'm running Brackets Stable, latest release.
