### ISSUE TITLE
Possible CodeMirror conflict with brackets-git

### ISSUE THREAD

**Issue by macbookandrew** [thehogfather/brackets-code-folding#119]
See https://github.com/zaggino/brackets-git/issues/909#issuecomment-74127468

Disabling either brackets-code-folding or brackets-git plugin solves the issue.

**Comment by thehogfather** [comment]
Are there any specific steps to reproduce this issue? The linked issue does not contain enough information to reproduce either. Cheers

**Comment by macbookandrew** [comment]
It now seems that it’s an issue with brackets-git, but I wasn’t sure at first so tagged you too. Thanks

**Comment by thehogfather** [comment]
It bothered me that there were errors related to the code-folding extensions in the console - so I'll reopen this issue. I'll push an update shortly and I'll appreciate it if you could test for any fixes.

**Comment by macbookandrew** [comment]
Sure—I’d be glad to help.

**Comment by thehogfather** [comment]
Great. Could you manually install the latest version of code-folding from [here](https://github.com/thehogfather/brackets-code-folding/archive/master.zip) and let me know if that has any impact.

**Comment by macbookandrew** [comment]
That appears to have fixed it—no more errors in the console, and the related issue with brackets-git is no longer happening.

Thanks!
