### ISSUE TITLE
Code folding does not persist

### ISSUE THREAD

**Issue by mandofever78** [thehogfather/brackets-code-folding#120]
Brackets version Release 1.1 build 1.1.0-15558 (release ea908cae5) 
Mac OSX 10.10
Brackets installed via Homebrew cask
uninstalled and reinstalled Brackets and cleared Brackets cache
uninstalled and reinstalled latest brackets-code-folding extension via Extension Manager
Also uninstalled and manually installed Edge compatible brackets-code-folding extension version 
No persistance after Brackets restart

**Comment by thehogfather** [comment]
Hi you should install the latest version of brackets and check the code folding preferences panel `View > Code Folding Settings...` and make sure that `Save Fold States` is checked. If this does not help please check if there are any error messages in the console `Debug > Show Developer Tools`
