### ISSUE TITLE
code folding breaking on titled for loops

### ISSUE THREAD

**Issue by keleko34** [thehogfather/brackets-code-folding#125]
when assigning a title to a for loop and the next line is not a bracketed item it will add a fold point to it breaking some fold points further down the line
![forloop bug](https://cloud.githubusercontent.com/assets/7937774/6423743/5ddf2068-be9f-11e4-995f-92289bb493e3.JPG)

**Comment by thehogfather** [comment]
Can you confirm you are using the latest version from github? You will have to install manually to test it out.

**Comment by keleko34** [comment]
ok thank you, did a manual install of the current version (0.3.1) on github which seemed to fix this.

**Comment by thehogfather** [comment]
no problem. I fixed a few bugs that I am yet to push to the registry.
