### ISSUE TITLE
Use character '|' on spanish keyboards

### ISSUE THREAD

**Issue by bramxu** [thehogfather/brackets-code-folding#127]
Hi!

I'm using Angular, and i use the character '|' a lot, but  on apple keyboard alt+1 collapse the code and i can't write this character. Can fix it??

Thanks for the extension! :dancer:

**Comment by thehogfather** [comment]
@bramxu  you can remap the keyboard shortcuts as described [here](https://github.com/adobe/brackets/wiki/User-Key-Bindings)

**Comment by bramxu** [comment]
ok!

Thanks for the info! :+1:
