### ISSUE TITLE
Uncheck "Enable code folding" from the settings issue

### ISSUE THREAD

**Issue by ostranme** [thehogfather/brackets-code-folding#133]
When you uncheck the "enable code folding" in the settings menu, the extension goes away completely. you can no longer get back to the settings of the code folding. Tried to uninstall and reinstall extension however still does not show up.

**Comment by thehogfather** [comment]
Could you open the preferences file `Debug > Open Preferences File` and change the codefolding enabled property to true. I will fix the user interface glitch sometime.

**Comment by ostranme** [comment]
Great thanks for letting me know about the preference file in the mean time. You can close issue if you want or keep it as a reminder.

**Comment by thehogfather** [comment]
i'll leave it open till I fix.

**Comment by ostranme** [comment]
thanks!
