### ISSUE TITLE
Beginning of lines in files are occluded

### ISSUE THREAD

**Issue by MortenAndersen** [thehogfather/brackets-code-folding#134]
Can't see the beginning of the lines in my SCSS files.

**Comment by thehogfather** [comment]
can you post a screenshot?

**Comment by MortenAndersen** [comment]
![code-folding](https://cloud.githubusercontent.com/assets/1526024/7228801/39ebf5d2-e75d-11e4-91d8-a21813cda283.gif)

:-)

**Comment by thehogfather** [comment]
Thanks for that. I'm however unable to reproduce the issue. Can I confirm that it happens only in scss files? and do you have other extensions that use the gutter?

**Comment by thehogfather** [comment]
Actually I can reproduce this on any file.

1. `Cmd-R` to Reload Brackets.

Effect is as described in issue - although the issue dissapears when the window is resized.

**Comment by MortenAndersen** [comment]
I can't confirm that the problem disappear when the window is resized.
It just revealed a little more of the code ... but not all

Extensions:
Adobe Edge Web Fonts
Autoprefixer
Beautify
Brackets Color Palette
Brackets Language Switcher
Brackets New Project Creator
Brackets SASS
Brackets SASS Code Hints
Brackets Snippets (by edc)
Brackets Tools
Code Outline
Extract for Brackets (Preview)
Inline Units Conversion
JSCompiler2
Lorem Pixel
Minifier
Notes
Simple To-Do
SVG Preview
W3CValidation

......

Code Folding

**Comment by clouchtibat** [comment]
I have the same problem, I managed to make it work by hiding and displaying the line numbers.

**Comment by gbam92** [comment]
Resizing the window didn't work for me, but hiding and showing line numbers did.

**Comment by Velunce** [comment]
Can't see the beginning of the lines in my html files.
![Uploading error.jpg . . .]()

**Comment by Velunce** [comment]
![error](https://cloud.githubusercontent.com/assets/7532346/7267918/f4b45948-e8f4-11e4-8192-710f92816933.jpg)

**Comment by douglasstarnes** [comment]
Toggling the line numbers off and then on shows the entire line, but then the gutter is about twice as wide as it was before the toggling.

**Comment by thehogfather** [comment]
This should now be fixed. Please update the extension to the latest in the registry and test.
Thanks all.

**Comment by douglasstarnes** [comment]
Works great now!  Thanks! :+1:

**Comment by MortenAndersen** [comment]
Nice :+1:
