### ISSUE TITLE
Version 0.3.4 doesn't fold

### ISSUE THREAD

**Issue by cipo28** [thehogfather/brackets-code-folding#135]
Hello, I'm using Brackets 1.2 but since the last update (20/04/15) the plugin has stopped working: it doesn't fold by triangles any kind of code. Only the (standard) ALT+1 keyboard shortcuts works (fold/unfold all, but without click reaction), the Ctrl-Alt-C press is captured by "Extract for Brackets".
-Tried to uninstalling every other plugins without any result.
-Running under Windows 8.1 64bit
-Has worked fine since the previous version with others plugins (minimap, code hints...)

**Comment by thehogfather** [comment]
I've just pushed an update to the registry. Could you install and check if this issue still exists? If it does, I will need some more information (e.g., any error messages in the developer console)

**Comment by cipo28** [comment]
0.3.5 installed and working perfectly, you're awesome!
Was the problem hard to find?

**Comment by thehogfather** [comment]
I could not reproduce the issue on my mac but I had to fix another issue - #134 - which i suspect might be related to this. I'll leave this issue open for a few more days - just in case it recurs.

Best
