### ISSUE TITLE
version not compatible :(

### ISSUE THREAD

**Issue by ghost** [thehogfather/brackets-code-folding#137]
Hey!
the version is not compatible....
![sem titulo](https://cloud.githubusercontent.com/assets/6217617/8091536/4491bc0c-0fac-11e5-87d4-4afed9cadd48.png)

**Comment by thehogfather** [comment]
@bl0zis you shouldnt need to install the extension for the latest version of brackets because code folding  has been part of brackets core since 1.3.
Could you let me know the version of brackets you are using?

**Comment by ghost** [comment]
@thehogfather Hey!
Yes, my version is 1.3, but code folder stop to work on .jade files :(

**Comment by thehogfather** [comment]
ah - have you tried enabling indentation folding? To do that, create a preference entry in your .brackets.json file for `"code-folding.alwaysUseIndentFold": true`

**Comment by ghost** [comment]
@thehogfather THANKS!
