### ISSUE TITLE
VI support for code folding

### ISSUE THREAD

**Issue by rick4470** [thehogfather/brackets-code-folding#138]
I'm not sure if this is a feature already or not. I'm using the [brackets vim](https://github.com/megalord/brackets-vim) plugin and the code folding works correctly except when I start to navigate through the document with `k j` each of the folds start to open automatically once the cursor is placed over them, is their a way to disable this?

![Example of code folding with vim and brackets](http://codewithintent.com/wp-content/uploads/2015/09/Screen-Shot-2015-09-27-at-11.17.19-AM.png)

**Comment by thehogfather** [comment]
At the moment that is not currently an option as the code-folding extension uses the default code mirror properties for marking text regions. The relevant property is `clearOnEnter: true` [see here](http://codemirror.net/doc/manual.html#markText).
May I ask whether you are using the default Code-folding extension shipped with Brackets or have you explicitly installed the extension from the registry?

**Comment by rick4470** [comment]
Thanks for the quick response, if it's not a an option i'm going to go ahead and close this issue then. Thought I would ask though, I'm using the default code folding that comes with Brackets.
