### ISSUE TITLE
What about Jade folding?

### ISSUE THREAD

**Issue by paulrevival** [thehogfather/brackets-code-folding#140]
Hey! :) It's a really cool feature and I pray for it :) But some time ago I've started to work with jade-syntax where it's much more difficult (for me yet) to detect a needed code-region then with html-syntax. It'd be simply wonderfull if Code folding would work with jade :) What do you think about it? (Sorry for my english)

**Comment by thehogfather** [comment]
@paulrevival jade structure looks like it is based on indentations and you can enable indentation based code-folding in brackets by adding this line to your `.brackets.json` file

``` javascript
    'code-folding.alwaysUseIndentFold': true
```
