### ISSUE TITLE
(imho) code-folding overloads state.json?

### ISSUE THREAD

**Issue by paulrevival** [thehogfather/brackets-code-folding#141]
Hello! I'm trying to find out why my Brackets (Ubuntu 14.04 + SSD + 8GB RAM) starts to work slower and slower while I'm working on more and more projects. Extantions disabling doesn't help me anyway. Then I tryed to open state.json file (~/.config/Brackets/) and.. even gedit stucked.. It's weight was 12.2 MB !!
Of course I've deleted it and Brackets started working fine (like it's just installed). So then I've opened some projects directories, used alt+1 hotkey in .scss/.less pane and opened a new state.json (created by Brackets automatically on start up). So I detected that 'code-folding.folds' object(or branch??) in state.json takes too much strings of 2-dim arrays with numbers (dots of folding starts and ends, yep?).
Of course if I'll open and then close lots of projects and use there code-folding ext, all of such folding-starts/ends will be written to this state.json.
How do you think (or maybe know?) is there any way to prevent such behavior? Maybe there is a way to remove such json branch from state.json when the project was closed?? It would be very cool, uh?))
Thanks for extantions and sorry for my english :)

**Comment by thehogfather** [comment]
If you don't want code-folding to save your fold states then add the following entry into your .brackets.json file

`"code-folding.saveFoldStates": false`

This will prevent the folded states from being saved by brackets when you close and reopen the IDE. I don't think there is much of a workaround for the issue beyond this. Dont forget that collapsing all the foldable regions in a large file is expensive (especially if you want to remember the state of the folds when brackets exits and reopens).

There is another preference setting that might be of interest. If you feel you need to use the `Alt-1` key combination frequently and you would like to persist the fold states, add the following setting to your `.brackets.json` file

`"code-folding.maxFoldLevel": 1`

Do tell if there are any other issues.

**Comment by paulrevival** [comment]
Thank you for the answer :) These options are exactly what I need !!
