### ISSUE TITLE
Unable to install extension

### ISSUE THREAD

**Issue by p8R** [thehogfather/brackets-code-folding#142]
In current version of Brackets (1.7, build 1.7.0-16898) extension is deactivated with the comment saying that it works only in older versions of the program.

**Comment by quirinux** [comment]
>  Please read
> 
> From release 1.3, code folding will be integrated into Brackets (although without custom region folding). This repository is still active for users who are running Brackets versions less than 1.3. If you are running 1.3 and would like custom region code folding you can find it here

**Comment by thehogfather** [comment]
Thanks @quirinux.
@p8R  code-folding has been integrated into Brackets. If you have any issues log it in the brackets repo.
