### ISSUE TITLE
Problem with the shortcut

### ISSUE THREAD

**Issue by nucliweb** [thehogfather/brackets-code-folding#80]
Hi,

in Mac OS with Spanish keyboard, we need cmd+1 for insert the | (pipeline).

**Comment by mathias7am** [comment]
I have a problem on Windows in french too. I don't understand how to remap the key. I installed the key remapper. With the menu Debug->Open Preference File, i opened keymap.json. But every thing i try like : 
```javascript
{
    "documentation": "https://github.com/adobe/brackets/wiki/User-Key-Bindings",
    "overrides": {
        "Collapse_All": ""
    }
}
```
trig a error

**Comment by thehogfather** [comment]
@mathias7am Could you replace "Collapse_All" with "codefolding.collapse.all" and see if that fixes the issue?
I will update the readme file accordingly. Also you no longer need to install the key-remapper plugin (since brackets now supports remapping keys natively).

Cheers

**Comment by mathias7am** [comment]
Solved :
```javascript
{
    "documentation": "https://github.com/adobe/brackets/wiki/User-Key-Bindings",
    "overrides": {
        "Ctrl-Alt-Shift-1": "codefolding.collapse.all" 
    }
}
```
Thanks a lot. ;-D
