### ISSUE TITLE
very very very slow in Linux

### ISSUE THREAD

**Issue by mb-programmer** [thehogfather/brackets-code-folding#81]
hi
this extension is a necessary tools in Brackets
i am using your extension on Ubuntu 
when i install this extension, my Brackets became very very very slow.
when i want to open a long file it takes around 10 seconds
and if i remove it every thing became fast again
thanks for great work

**Comment by cotrk** [comment]
I'm finding brackets running slow and even locks up sometimes in Ubuntu. Been using Sublime in the mean time. :(
